package com.tschasmine.dependency.analysis.app

enum class Colors {
    Blue,
    Darkcyan,
    Forestgreen,
    Purple,
    Red,
    Olivedrab,
    Darkorange,
    Cornflowerblue,
    Indianred,
    Darkmagenta,
    Darkkhaki,
    Deeppink,
    Teal,
    Steelblue,
    Firebrick,
    Peru,
    Pink,
    Seagreen,
    Moccasin,
    Darkviolet,
    Limegreen,
    Olive,
    Crimson,
    Brown,
    Coral,
    Darkslategray,
    Chartreuse,
    Paleturquoise,
    Lavenderblush,
    Orchid,
    Lightblue
}
